name: ZAP Baseline Scan

on: workflow_dispatch

permissions:
  contents: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install pip and poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.8.2
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Cache the virtualenv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Download NLP model
        run: |
          python -m poetry run python -m spacy download en_core_web_sm
      - name: Start Flask dev server
        run: |
          python -m poetry run flask --app speak_to_data/presentation/app.py run &

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          allow_issue_writing: "false"
